sudo: required

language: csharp
solution: SpeakOps.Api.sln
mono: none
dotnet: 2.1.4

services:
  - docker
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jq
  
install:
  - dotnet restore
  
script:
  - dotnet build
  - dotnet test SpeakOps.Api.AcceptanceTests/SpeakOps.Api.AcceptanceTests.csproj
  
deploy:
  provider: script
  script: bash docker_push_ecs_deploy
  on:
    branch: MigrateToAws