sudo: required

language: csharp
solution: SpeakOps.Api.sln
mono: none
dotnet: 2.1.4

services:
  - docker
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jq
  - docker pull postgres:alpine
  - docker run -d -p 127.0.0.1:5435:5432 postgres:alpine
  - docker ps -a
  
install:
  - dotnet restore
  
script:
  - dotnet build
  - find . -print | grep -i -e '.*tests.csproj$' | dotnet test
  
deploy:
  provider: script
  script: bash docker_push_ecs_deploy
  on:
    branch: master