language: csharp
solution: SpeakOps.Api.sln
mono: none
dotnet: 2.1.4

install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test SpeakOps.Api.AcceptanceTests/SpeakOps.Api.AcceptanceTests.csproj