api:
  build: .
  links:
    - postgres
  ports:
    - "5000:5000"
    
postgres:
  image: postgres:alpine
  restart: unless-stopped
  environment:
    - POSTGRES_PASSWORD=Spe@k0ps
  ports:
    - "5435:5432"